routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\SatuanBarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ReturBarangController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\TokoController;
use App\Http\Controllers\TransaksiKeluarController;
use App\Http\Controllers\DetailBarangController;
use App\Http\Controllers\DetailMasukController;
use App\Http\Controllers\DetailKeluarController;
use App\Http\Controllers\DetailReturController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\PenggantianBarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('landing_page');
});

// Route::get('/dash', function () {   
//     return view('app');
// });

Auth::routes();

Route::prefix('admin')->middleware(['auth', 'isAdmin'])->group(function(){
    Route::get('/beranda', [DashboardAdminController::class, 'dashboard'])->name('admin.beranda');
    Route::resource('admin', AdminController::class);
    Route::get('/kategori', [KategoriBarangController::class, 'adminKategori'])->name('kategori');
    Route::get('/satuan', [SatuanBarangController::class, 'adminSatuan'])->name('satuan');
    Route::get('/barang', [BarangController::class, 'adminBarang'])->name('barang');
    Route::get('/detailbrg', [BarangController::class, 'adminDetailBrg'])->name('detailbrg');
    Route::resource('supplier', SupplierController::class);
    Route::get('/dashboardadm', [DashboardAdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::match(['get','post'],'/lapmasuk', [TransaksiMasukController::class, 'lapmasuk'])->name('lapmasuk');
    Route::match(['get','post'],'/lapmasuk/export', [TransaksiMasukController::class, 'exportPDF'])->name('export_lapmasuk');
    Route::match(['get', 'post'], '/lapkeluar', [TransaksiKeluarController::class, 'lapkeluar'])->name('lapkeluar');
    Route::match(['get','post'],'/lapkeluar/export', [TransaksiKeluarController::class, 'exportPDF'])->name('export_lapkeluar');
    Route::get('/lapsupplier', [SupplierController::class, 'lapSupplier'])->name('lapSupplier');
    Route::match(['get','post'],'/lapsupplier/export', [SupplierController::class, 'exportPDF'])->name('export_lapsupplier');
    Route::match(['get', 'post'], '/lapretur', [ReturBarangController::class, 'lapretur'])->name('lapretur');
    Route::match(['get','post'],'/lapretur/export', [ReturBarangController::class, 'exportPDF'])->name('export_lapretur');
    Route::match(['get', 'post'], '/lappenggantian', [PenggantianBarangController::class, 'lappenggantian'])->name('lappenggantian');
    Route::match(['get','post'],'/lappenggantian/export', [PenggantianBarangController::class, 'exportPDF'])->name('export_lappenggantian');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home.user');
Route::get('/welcome', [DashboardController::class, 'dashboard'])->name('home.welcome');
// Route::resource('/kategori', [KategoriBarangController::class]);
Route::get('/petugas', [HomeController::class, 'pengguna'])->name('petugas.pengguna');
Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('petugas.dashboard');
Route::resource('petugas', PetugasController::class);
Route::resource('kategori', KategoriBarangController::class);
Route::resource('satuan', SatuanBarangController::class);

Route::resource('retur', ReturBarangController::class);
Route::resource('barang', BarangController::class);
Route::resource('trmasuk', TransaksiMasukController::class);
Route::post('trmasuk/filterTransMasuk', [TransaksiMasukController::class, 'filterTransMasuk'])->name('trmasuk.filterTransMasuk');
Route::get('/modal-content', [TransaksiMasukController::class, 'modalContent'])->name('trmasuk.modalContent');
Route::resource('toko', TokoController::class);
Route::resource('trkeluar', TransaksiKeluarController::class);
Route::post('trkeluar/filterTransKeluar', [TransaksiKeluarController::class, 'filterTransKeluar'])->name('trkeluar.filterTransKeluar');
Route::resource('detailbrg', DetailBarangController::class);
Route::resource('detailmasuk', DetailMasukController::class);
Route::get('/detail_masuk/fetch', [DetailMasukController::class, 'fetch'])->name('detail_masuk.fetch');
Route::resource('detailkeluar', DetailKeluarController::class);
Route::get('/get_stok/{idDetailBarang}', [DetailKeluarController::class, 'getStok']);
Route::resource('detailretur', DetailReturController::class);
Route::get('/retur_stok/{idDetailBarang}', [DetailReturController::class, 'stokRetur']);
Route::resource('penggantianbarang', PenggantianBarangController::class);
Route::get('/get_jumlah_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getJumlahRetur'])->name('retur.getJumlahRetur');
Route::get('/get_detail_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getDetailRetur']);
Route::get('/get_detail_barang/{idDetailBarang}', [PenggantianBarangController::class, 'getDetailBarang']);
Route::get('/get-supplier-name', [DetailMasukController::class, 'getSupplierName']);

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin | PT. Gudang Lancar Jaya</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghdjkPvT3KUIKqUf7xvePIjIwTkK+" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  @stack('custom_css')
</head>

<body>
  <!-- Navbar -->
  @include('header_admin')
  <!-- ./navbar -->
  <!-- Main Sidebar Container -->
  @include('admin.sidebar')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="background-color: #ffffff">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->
  @include('footer')
  <!-- jQuery -->
  <script src="{{asset('assets/plugins/jQuery/jQuery-2.1.3.min.js')}}"></script>
  <!-- Bootstrap 4 -->
  <script src="{{asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset('assets/dist/js/adminlte.min.js')}}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{{asset('assets/dist/js/demo.js')}}"></script>
  @stack('custom_js')
</body>

</html>

resources/views/admin/create.blade.php
@extends('admin.app')
@section('content')
<div class="container mt-5">
   <div class="row justify-content-center align-items-center">
   <div class="card" style="width: 24rem;">
   <div class="card-header">Tambah Petugas</div>
   
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">      
         <strong>Whoops!</strong> There were some problems with your input.<br><br>
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      @endif
      
      <form method="post" action="{{ route('admin.store') }}" id="myForm">
         @csrf
         <div class="form-group">
            <label for="idUser">ID User</label> 
            <input type="text" name="idUser" class="form-control" id="idUser" aria-describedby="idUser" > 
         </div>
         <div class="form-group">
            <label for="nama">Nama</label> 
            <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" > 
         </div>
         <div class="form-group">
            <label for="umur">Umur</label> 
            <input type="text" name="umur" class="form-control" id="umur" aria-describedby="umur" > 
         </div>
         <div class="form-group">
            <label for="alamat">Alamat</label> 
            <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="alamat" > 
         </div>
         <div class="form-group">
            <label for="username">Username</label> 
            <input type="text" name="username" class="form-control" id="username" aria-describedby="username" > 
         </div>
         <div class="form-group">
            <label for="password">Password</label> 
            <input type="password" name="password" class="form-control" id="password" aria-describedby="password" > 
         </div>
         <div class="form-group">
            <label for=" noTelp">No Telepon</label> 
            <input type="text" name="noTelp" class="form-control" id="noTelp" aria-describedby="noTelp" > 
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>
</div>
</div>
</div>
@endsection

resources/views/admin/detail.blade.php
@extends('admin.app')
@section('content')
@if($showModal)

<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalShow').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalShow">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Detail Data Pengguna</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>ID User</b>{{$admin->idUser}}</li>
                    <li class="list-group-item"><b>Nama</b>{{$admin->nama}}</li>
                    <li class="list-group-item"><b>Umur</b>{{$admin->umur}}</li>
                    <li class="list-group-item"><b>Alamat</b>{{$admin->alamat}}</li>
                    <li class="list-group-item"><b>Username</b>{{$admin->username}}</li>
                    <li class="list-group-item"><b>No Telepon</b>{{$admin->noTelp}}</li>
                </ul>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('admin.index') }}">Kembali</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('admin.app')
<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
@section('content')
@if($showModal)
<script>
    $(document).ready(function() {
        $('#modalEdit').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit User</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
            <form method="post" action="{{ route('admin.update', $admin->idUser) }}" id="myForm">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="idUser">ID User</label> 
                    <input type="text" name="idUser" class="form-control" id="idUser" value="{{ $admin->idUser }}" aria-describedby="idUser" > 
                </div>
                <div class="form-group">
                    <label for="nama">Nama</label> 
                    <input type="text" name="nama" class="form-control" id="nama" value="{{ $admin->nama }}" aria-describedby="nama" > 
                </div>
                <div class="form-group">
                    <label for="umur">Umur</label>
                    <input type="text" name="umur" class="form-control" id="umur" value="{{ $admin->umur }}" aria-describedby="umur" > 
                </div>
                <div class="form-group">
                    <label for="alamat">Alamat</label> 
                    <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $admin->alamat }}" aria-describedby="alamat" > 
                </div>
                <div class="form-group">
                    <label for="username">Username</label> 
                    <input type="text" name="username" class="form-control" id="username" value="{{ $admin->username }}" aria-describedby="username" > 
                </div>
                <div class="form-group">
                    <label for="password">Password</label> 
                    <input type="password" name="password" class="form-control" id="password" value="{{ $admin->password }}" aria-describedby="password" > 
                </div>
                <div class="form-group">
                    <label for="noTelp">No Telepon</label> 
                    <input type="text" name="noTelp" class="form-control" id="noTelp" value="{{ $admin->noTelp }}" aria-describedby="noTelp" > 
                </div>
                <div class="form-group">
                    <label for="role">Role</label> 
                    <input type="text" name="role" class="form-control" id="role" value="{{ $admin->role }}" aria-describedby="role" > 
                </div>
                <button type="submit" class="btn-action btn-submit">Submit</button>
            </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('admin.index') }}">Kembali</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('admin.app')
@section('content')

<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>

<br>
<div class="col-md-12 d-flex flex-row justify-content-end" data-toggle="modal" data-target="#myModal">
    <a class="btn rounded-pill" style="background: linear-gradient(to right, #6c63ff, #a892ff); color: white; padding: 12px 16px; font-size: 24px; margin-left: -8px;">
        <i class="fas fa-plus"></i>
    </a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title font-weight-bold" style="margin-top:15px;">Data Pengguna</h3><br>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID User</th>
                            <th>Nama</th>
                            <th>Umur</th>
                            <th>Alamat</th>
                            <th>Username</th>
                            <th>No Telp</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($admin as $ptg)
                        <tr>
                            <td>{{ $ptg->idUser }}</td>
                            <td>{{ $ptg->nama }}</td>
                            <td>{{ $ptg->umur }}</td>
                            <td>{{ $ptg->alamat }}</td>
                            <td>{{ $ptg->username }}</td>
                            <td>{{ $ptg->noTelp }}</td>
                            <td>
                                <form action="{{ route('admin.destroy',$ptg->idUser) }}" method="POST">
                                    <a class="btn-action btn-show" href="{{ route('admin.show',$ptg->idUser) }}">Show</a>
                                    <a class="btn-action btn-edit" href="{{ route('admin.edit',$ptg->idUser) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    @if ($ptg->count() > 1)
                                    <button type="submit" class="btn-action btn-delete">Delete</button>
                                    @endif
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Tambah Data User</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('admin.store') }}" id="myForm">
                    @csrf
                    <div class="form-group">
                        <label for="idUser">ID User</label>
                        <input type="text" name="idUser" class="form-control" id="idUser" aria-describedby="idUser" >
                    </div>
                    <div class="form-group">
                        <label for="nama">Nama User</label>
                        <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" >
                    </div>
                    <div class="form-group">
                        <label for="umur">Umur User</label>
                        <input type="text" name="umur" class="form-control" id="umur" aria-describedby="umur" >
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="alamat" >
                    </div>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" id="username" aria-describedby="username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" aria-describedby="password">
                    </div>
                    <div class="form-group">
                        <label for=" noTelp">No Telepon</label>
                        <input type="text" name="noTelp" class="form-control" id="noTelp" aria-describedby="noTelp" >
                    </div>
                    <button type="submit" class="btn rounded" style="background-color: #282A3A; color: white;">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

    <div class="col-md-12">
        <ul class="pagination">
            {{ $admin->links() }}
        </ul>
    </div>
</section>
@endsection

resources/views/admin/sidebar.blade.php
<style>
  .main-sidebar {
    background-color: #6c63ff;
  }

  .brand-link {
    background-color: #6c63ff;
  }

  .brand-link .brand-image {
    border: none;
  }

  .brand-link .brand-text {
    color: #ffffff;
    font-size: 1.2rem;
  }

  .sidebar-search .form-control {
    background-color: #293462;
    color: #d3d9de;
    border-color: transparent;
  }

  .sidebar-search .btn-sidebar {
    background-color: #293462;
    color: #d3d9de;
  }

  .nav-sidebar .nav-link {
    color: #ffffff;
  }

  .nav-sidebar .nav-link:hover {
    color: #c3bdff;
  }

  .nav-sidebar .nav-icon {
    color: #c3bdff;
  }

  .nav-sidebar .right {
    color: #c3bdff;
  }
</style>

<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <a href="{{ route('admin.dashboard') }}" class="brand-link mt-2">
    <img src="{{ asset('land/images/logo_glj.jpg') }}" alt="Logo" class="brand-image img-thumbnail elevation-3">
    <span class="brand-text font-weight-bold" style="font-size:medium;">PT. Gudang Lancar Jaya</span>
  </a>
  <div class="sidebar sidebar-content">
    <br>
    <div class="form-inline"> 
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar bg-white" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar" style="background-color: white;">
            <i class="fas fa-search fa-fw"  style="color: #6c63ff;"></i>
          </button>
        </div>
      </div>
    </div>


    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="{{ route('admin.dashboard') }}" class="nav-link">
            <i class="nav-icon fas fa-solid fa-th-large"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.index') }}" class="nav-link">
            <i class="nav-icon fas fa-solid fa-users"></i>
            <p>
              Data Pengguna
            </p>
          </a>
        </li>
        <li class="nav-item menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-database"></i>
            <p>
              Data Master
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{ route('barang') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Data Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('detailbrg') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Detail Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('kategori') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Kategori Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('satuan') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Satuan Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('supplier.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Data Supplier</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-exchange-alt"></i>
            <p>
              Data Retur
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{ route('retur.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Retur Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('detailretur.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Detail Retur</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('penggantianbarang.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Penggantian Barang</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-print"></i>
            <p>
              Laporan
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{ route('lapmasuk') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Laporan Barang Masuk</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('lapkeluar') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Laporan Barang Keluar</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('lapSupplier') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Laporan Data Supplier</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('lapretur') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Laporan Retur Barang</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('lappenggantian') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Laporan Penggantian</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="{{ route('logout') }}" class="nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              {{ __('Logout') }}
            </p>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
              @csrf
            </form>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</aside>