routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\SatuanBarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ReturBarangController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\TokoController;
use App\Http\Controllers\TransaksiKeluarController;
use App\Http\Controllers\DetailBarangController;
use App\Http\Controllers\DetailMasukController;
use App\Http\Controllers\DetailKeluarController;
use App\Http\Controllers\DetailReturController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\PenggantianBarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('landing_page');
});

// Route::get('/dash', function () {   
//     return view('app');
// });

Auth::routes();

Route::prefix('admin')->middleware(['auth', 'isAdmin'])->group(function(){
    Route::get('/beranda', [DashboardAdminController::class, 'dashboard'])->name('admin.beranda');
    Route::resource('admin', AdminController::class);
    Route::get('/kategori', [KategoriBarangController::class, 'adminKategori'])->name('kategori');
    Route::get('/satuan', [SatuanBarangController::class, 'adminSatuan'])->name('satuan');
    Route::get('/barang', [BarangController::class, 'adminBarang'])->name('barang');
    Route::get('/detailbrg', [BarangController::class, 'adminDetailBrg'])->name('detailbrg');
    Route::resource('supplier', SupplierController::class);
    Route::get('/dashboardadm', [DashboardAdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::match(['get','post'],'/lapmasuk', [TransaksiMasukController::class, 'lapmasuk'])->name('lapmasuk');
    Route::match(['get','post'],'/lapmasuk/export', [TransaksiMasukController::class, 'exportPDF'])->name('export_lapmasuk');
    Route::match(['get', 'post'], '/lapkeluar', [TransaksiKeluarController::class, 'lapkeluar'])->name('lapkeluar');
    Route::match(['get','post'],'/lapkeluar/export', [TransaksiKeluarController::class, 'exportPDF'])->name('export_lapkeluar');
    Route::get('/lapsupplier', [SupplierController::class, 'lapSupplier'])->name('lapSupplier');
    Route::match(['get','post'],'/lapsupplier/export', [SupplierController::class, 'exportPDF'])->name('export_lapsupplier');
    Route::match(['get', 'post'], '/lapretur', [ReturBarangController::class, 'lapretur'])->name('lapretur');
    Route::match(['get','post'],'/lapretur/export', [ReturBarangController::class, 'exportPDF'])->name('export_lapretur');
    Route::match(['get', 'post'], '/lappenggantian', [PenggantianBarangController::class, 'lappenggantian'])->name('lappenggantian');
    Route::match(['get','post'],'/lappenggantian/export', [PenggantianBarangController::class, 'exportPDF'])->name('export_lappenggantian');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home.user');
Route::get('/welcome', [DashboardController::class, 'dashboard'])->name('home.welcome');
// Route::resource('/kategori', [KategoriBarangController::class]);
Route::get('/petugas', [HomeController::class, 'pengguna'])->name('petugas.pengguna');
Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('petugas.dashboard');
Route::resource('petugas', PetugasController::class);
Route::resource('kategori', KategoriBarangController::class);
Route::resource('satuan', SatuanBarangController::class);

Route::resource('retur', ReturBarangController::class);
Route::resource('barang', BarangController::class);
Route::resource('trmasuk', TransaksiMasukController::class);
Route::post('trmasuk/filterTransMasuk', [TransaksiMasukController::class, 'filterTransMasuk'])->name('trmasuk.filterTransMasuk');
Route::get('/modal-content', [TransaksiMasukController::class, 'modalContent'])->name('trmasuk.modalContent');
Route::resource('toko', TokoController::class);
Route::resource('trkeluar', TransaksiKeluarController::class);
Route::post('trkeluar/filterTransKeluar', [TransaksiKeluarController::class, 'filterTransKeluar'])->name('trkeluar.filterTransKeluar');
Route::resource('detailbrg', DetailBarangController::class);
Route::resource('detailmasuk', DetailMasukController::class);
Route::get('/detail_masuk/fetch', [DetailMasukController::class, 'fetch'])->name('detail_masuk.fetch');
Route::resource('detailkeluar', DetailKeluarController::class);
Route::get('/get_stok/{idDetailBarang}', [DetailKeluarController::class, 'getStok']);
Route::resource('detailretur', DetailReturController::class);
Route::get('/retur_stok/{idDetailBarang}', [DetailReturController::class, 'stokRetur']);
Route::resource('penggantianbarang', PenggantianBarangController::class);
Route::get('/get_jumlah_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getJumlahRetur'])->name('retur.getJumlahRetur');
Route::get('/get_detail_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getDetailRetur']);
Route::get('/get_detail_barang/{idDetailBarang}', [PenggantianBarangController::class, 'getDetailBarang']);
Route::get('/get-supplier-name', [DetailMasukController::class, 'getSupplierName']);

resources/views/admin/data_retur/detail.blade.php
@extends('admin.app')
@section('content')
@if($showModal)
<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalShow').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalShow">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Detail Data Retur</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>ID Retur</b>{{$retur->idRetur}}</li>
                    <li class="list-group-item"><b>ID Transaksi Masuk</b>{{$retur->idTransaksiMasuk}}</li>
                    <li class="list-group-item"><b>ID User</b>{{$retur->idUser}}</li>
                    <li class="list-group-item"><b>Tanggal Retur</b>{{$retur->tglRetur}}</li>
                </ul>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('retur.index') }}">Kembali</a>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/admin/data_retur/edit.blade.php
@extends('admin.app')
@section('content')
@if($showModal)
<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalEdit').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Data Retur Barang</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('retur.update', $retur->idRetur) }}" id="myForm">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="idRetur">ID Retur</label>
                        <input type="text" name="idRetur" class="form-control" id="idRetur" value="{{ old('idRetur', $retur->idRetur) }}" aria-describedby="idRetur">
                    </div>
                    <div class="form-group">
                        <label for="idTransaksiMasuk">ID Transaksi Masuk</label>
                        <select name="idTransaksiMasuk" class="form-control" id="idTransaksiMasuk">
                            <option value="">-- Pilih ID Transaksi Masuk --</option>
                            @foreach($trmasuk as $tm)
                            <option value="{{ $tm->idTransaksiMasuk }}" data-supplier="{{ $tm->suppliers->idSupplier }}">{{ $tm->idTransaksiMasuk }} || {{ $tm->suppliers->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="idUser">ID User</label>
                        <input type="text" name="idUser" class="form-control" id="idUser" value="{{ Auth::user()->idUser }}">
                        <small>Username: {{ Auth::user()->username }}</small>
                    </div>
                    <div class="form-group">
                        <label for="tglRetur">Tanggal Retur</label>
                        <input type="date" name="tglRetur" class="form-control" id="tglRetur" value="{{ old('tglRetur', $retur->tglRetur) }}" aria-describedby="tglRetur">
                    </div>
                    <button type="submit" class="btn-action btn-submit">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('retur.index') }}">Kembali</a>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/data_retur/index.blade.php
@extends('admin.app')
@section('content')

<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<br>
<div class="col-md-12 d-flex flex-row justify-content-end" data-toggle="modal" data-target="#myModal">
    <a class="btn rounded-pill" style="background: linear-gradient(to right, #6c63ff, #a892ff); color: white; padding: 12px 16px; font-size: 24px; margin-left: -8px;">
        <i class="fas fa-plus"></i>
    </a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title font-weight-bold" style="margin-top:15px;">Data Retur</h3><br>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID Retur</th>
                            <th>ID Transaksi Masuk</th>
                            <th>ID User</th>
                            <th>Tanggal Retur</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($retur as $r)
                        <tr>
                            <td>{{ $r -> idRetur}}</td>
                            <td>
                                {{ $r -> idTransaksiMasuk}}
                                @if($r->trmasuk)
                                <p style="font-weight: bold; font-size: 17px;">{{ $r->trmasuk->suppliers->nama }}</p>
                                @endif
                            </td>
                            <td>
                                {{ $r -> idUser}}
                                @if($r->admin)
                                <p style="font-weight: bold; font-size: 17px;">{{ $r->admin->nama }}</p>
                                @endif
                            </td>
                            <td>{{ $r -> tglRetur}}</td>
                            <td>
                                <form action="{{ route('retur.destroy',$r->idRetur) }}" method="POST">
                                    <a class="btn-action btn-show" href="{{ route('retur.show',$r->idRetur) }}">Show</a>
                                    <a class="btn-action btn-edit" href="{{ route('retur.edit',$r->idRetur) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-action btn-delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Tambah Data Retur</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('retur.store') }}" id="myForm" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="idRetur">ID Retur</label>
                        <input type="text" name="idRetur" class="form-control" id="idRetur" aria-describedby="idRetur">
                    </div>
                    <div class="form-group">
                        <label for="idTransaksiMasuk">ID Transaksi Masuk</label>
                        <select name="idTransaksiMasuk" class="form-control" id="idTransaksiMasuk">
                            <option value="">-- Pilih ID Transaksi Masuk --</option>
                            @foreach($trmasuk as $tm)
                            <option value="{{ $tm->idTransaksiMasuk }}" data-supplier="{{ $tm->suppliers->idSupplier }}">{{ $tm->idTransaksiMasuk }} || {{ $tm->suppliers->nama }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="idUser">ID User</label>
                        <input type="text" name="idUser" class="form-control" id="idUser" value="{{ Auth::user()->idUser }}">
                        <small>Nama Admin: {{ Auth::user()->nama }}</small>
                    </div>
                    <div class="form-group">
                        <label for="tglRetur">Tanggal Retur</label>
                        <input type="date" name="tglRetur" class="form-control" id="tglRetur" aria-describedby="tglRetur">
                    </div>
                    <button type="submit" class="btn rounded" style="background-color: #282A3A; color: white;">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<div class="col-md-12">
    <ul class="pagination">
        {{ $retur->links() }}
    </ul>
</div>
@endsection