routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\SatuanBarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ReturBarangController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\TokoController;
use App\Http\Controllers\TransaksiKeluarController;
use App\Http\Controllers\DetailBarangController;
use App\Http\Controllers\DetailMasukController;
use App\Http\Controllers\DetailKeluarController;
use App\Http\Controllers\DetailReturController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\PenggantianBarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('landing_page');
});

// Route::get('/dash', function () {   
//     return view('app');
// });

Auth::routes();

Route::prefix('admin')->middleware(['auth', 'isAdmin'])->group(function(){
    Route::get('/beranda', [DashboardAdminController::class, 'dashboard'])->name('admin.beranda');
    Route::resource('admin', AdminController::class);
    Route::get('/kategori', [KategoriBarangController::class, 'adminKategori'])->name('kategori');
    Route::get('/satuan', [SatuanBarangController::class, 'adminSatuan'])->name('satuan');
    Route::get('/barang', [BarangController::class, 'adminBarang'])->name('barang');
    Route::get('/detailbrg', [BarangController::class, 'adminDetailBrg'])->name('detailbrg');
    Route::resource('supplier', SupplierController::class);
    Route::get('/dashboardadm', [DashboardAdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::match(['get','post'],'/lapmasuk', [TransaksiMasukController::class, 'lapmasuk'])->name('lapmasuk');
    Route::match(['get','post'],'/lapmasuk/export', [TransaksiMasukController::class, 'exportPDF'])->name('export_lapmasuk');
    Route::match(['get', 'post'], '/lapkeluar', [TransaksiKeluarController::class, 'lapkeluar'])->name('lapkeluar');
    Route::match(['get','post'],'/lapkeluar/export', [TransaksiKeluarController::class, 'exportPDF'])->name('export_lapkeluar');
    Route::get('/lapsupplier', [SupplierController::class, 'lapSupplier'])->name('lapSupplier');
    Route::match(['get','post'],'/lapsupplier/export', [SupplierController::class, 'exportPDF'])->name('export_lapsupplier');
    Route::match(['get', 'post'], '/lapretur', [ReturBarangController::class, 'lapretur'])->name('lapretur');
    Route::match(['get','post'],'/lapretur/export', [ReturBarangController::class, 'exportPDF'])->name('export_lapretur');
    Route::match(['get', 'post'], '/lappenggantian', [PenggantianBarangController::class, 'lappenggantian'])->name('lappenggantian');
    Route::match(['get','post'],'/lappenggantian/export', [PenggantianBarangController::class, 'exportPDF'])->name('export_lappenggantian');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home.user');
Route::get('/welcome', [DashboardController::class, 'dashboard'])->name('home.welcome');
// Route::resource('/kategori', [KategoriBarangController::class]);
Route::get('/petugas', [HomeController::class, 'pengguna'])->name('petugas.pengguna');
Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('petugas.dashboard');
Route::resource('petugas', PetugasController::class);
Route::resource('kategori', KategoriBarangController::class);
Route::resource('satuan', SatuanBarangController::class);

Route::resource('retur', ReturBarangController::class);
Route::resource('barang', BarangController::class);
Route::resource('trmasuk', TransaksiMasukController::class);
Route::post('trmasuk/filterTransMasuk', [TransaksiMasukController::class, 'filterTransMasuk'])->name('trmasuk.filterTransMasuk');
Route::get('/modal-content', [TransaksiMasukController::class, 'modalContent'])->name('trmasuk.modalContent');
Route::resource('toko', TokoController::class);
Route::resource('trkeluar', TransaksiKeluarController::class);
Route::post('trkeluar/filterTransKeluar', [TransaksiKeluarController::class, 'filterTransKeluar'])->name('trkeluar.filterTransKeluar');
Route::resource('detailbrg', DetailBarangController::class);
Route::resource('detailmasuk', DetailMasukController::class);
Route::get('/detail_masuk/fetch', [DetailMasukController::class, 'fetch'])->name('detail_masuk.fetch');
Route::resource('detailkeluar', DetailKeluarController::class);
Route::get('/get_stok/{idDetailBarang}', [DetailKeluarController::class, 'getStok']);
Route::resource('detailretur', DetailReturController::class);
Route::get('/retur_stok/{idDetailBarang}', [DetailReturController::class, 'stokRetur']);
Route::resource('penggantianbarang', PenggantianBarangController::class);
Route::get('/get_jumlah_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getJumlahRetur'])->name('retur.getJumlahRetur');
Route::get('/get_detail_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getDetailRetur']);
Route::get('/get_detail_barang/{idDetailBarang}', [PenggantianBarangController::class, 'getDetailBarang']);
Route::get('/get-supplier-name', [DetailMasukController::class, 'getSupplierName']);

resources/views/admin/data_supplier/detail.blade.php
@extends('admin.app')
@section('content')
@if($showModal)
<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalShow').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalShow">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Detail Data Supplier</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>ID Supplier</b>{{$supplier->idSupplier}}</li>
                    <li class="list-group-item"><b>Nama Supplier</b>{{$supplier->nama}}</li>
                    <li class="list-group-item"><b>Alamat</b>{{$supplier->alamat}}</li>
                    <li class="list-group-item"><b>No Telepon</b>{{$supplier->noTelp}}</li>
                </ul>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('supplier.index') }}">Kembali</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/data_supplier/edit.blade.php
@extends('admin.app')
@section('content')
@if($showModal)

<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalEdit').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Data Supplier</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('supplier.update', $supplier->idSupplier) }}" id="myForm">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="idSupplier">ID Supplier</label>
                        <input type="text" name="idSupplier" class="form-control" id="idSupplier" value="{{ old('idSupplier', $supplier->idSupplier) }}" aria-describedby="idSupplier">
                    </div>
                    <div class="form-group">
                        <label for="nama">Nama Supplier</label>
                        <input type="text" name="nama" class="form-control" id="nama" value="{{ old('nama', $supplier->nama) }}" aria-describedby="nama">
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat Supplier</label>
                        <input type="text" name="alamat" class="form-control" id="alamat" value="{{ old('alamat', $supplier->alamat) }}" aria-describedby="alamat">
                    </div>
                    <div class="form-group">
                        <label for="noTelp">No Telepon</label>
                        <input type="text" name="noTelp" class="form-control" id="noTelp" value="{{ old('noTelp', $supplier->noTelp) }}" aria-describedby="noTelp">
                    </div>
                    <button type="submit" class="btn rounded" style="background-color: #282A3A; color: white;">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('supplier.index') }}">Kembali</a>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/data_supplier/index.blade.php
@extends('admin.app')
@section('content')

<head>
    <link rel="stylesheet" href="{{asset('assets/css/admin.css')}}">
</head>
<br>
<div class="col-md-12 d-flex flex-row justify-content-end" data-toggle="modal" data-target="#myModal">
    <a class="btn rounded-pill" style="background: linear-gradient(to right, #6c63ff, #a892ff); color: white; padding: 12px 16px; font-size: 24px; margin-left: -8px;">
        <i class="fas fa-plus"></i>
    </a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title font-weight-bold" style="margin-top: 15px;">Data Supplier</h3><br>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID Supplier</th>
                            <th>Nama Supplier</th>
                            <th>Alamat</th>
                            <th>No Telp</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($supplier as $sup)
                        <tr>
                            <td>{{ $sup -> idSupplier}}</td>
                            <td>{{ $sup -> nama}}</td>
                            <td>{{ $sup -> alamat}}</td>
                            <td>{{ $sup -> noTelp}}</td>
                            <td>
                                <form action="{{ route('supplier.destroy',$sup->idSupplier) }}" method="POST">
                                    <a class="btn-action btn-show" href="{{ route('supplier.show',$sup->idSupplier) }}">Show</a>
                                    <a class="btn-action btn-edit" href="{{ route('supplier.edit',$sup->idSupplier) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-action btn-delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Tambah Data Supplier</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('supplier.store') }}" id="myForm">
                    @csrf
                    <div class="form-group">
                        <label for="idSupplier">ID Supplier</label>
                        <input type="text" name="idSupplier" class="form-control" id="idSupplier" aria-describedby="idSupplier">
                    </div>
                    <div class="form-group">
                        <label for="nama">Nama Supplier</label>
                        <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama">
                    </div>
                    <div class="form-group">
                        <label for="alamat">Alamat</label>
                        <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="alamat">
                    </div>
                    <div class="form-group">
                        <label for=" noTelp">No Telepon</label>
                        <input type="text" name="noTelp" class="form-control" id="noTelp" aria-describedby="noTelp">
                    </div>
                    <button type="submit" class="btn rounded" style="background-color: #282A3A; color: white;">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>
<div class="col-md-12">
    <ul class="pagination">
        {{ $supplier->links() }}
    </ul>
</div>
@endsection