routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KategoriBarangController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\SatuanBarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\ReturBarangController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\TokoController;
use App\Http\Controllers\TransaksiKeluarController;
use App\Http\Controllers\DetailBarangController;
use App\Http\Controllers\DetailMasukController;
use App\Http\Controllers\DetailKeluarController;
use App\Http\Controllers\DetailReturController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\PenggantianBarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('landing_page');
});

// Route::get('/dash', function () {   
//     return view('app');
// });

Auth::routes();

Route::prefix('admin')->middleware(['auth', 'isAdmin'])->group(function(){
    Route::get('/beranda', [DashboardAdminController::class, 'dashboard'])->name('admin.beranda');
    Route::resource('admin', AdminController::class);
    Route::get('/kategori', [KategoriBarangController::class, 'adminKategori'])->name('kategori');
    Route::get('/satuan', [SatuanBarangController::class, 'adminSatuan'])->name('satuan');
    Route::get('/barang', [BarangController::class, 'adminBarang'])->name('barang');
    Route::get('/detailbrg', [BarangController::class, 'adminDetailBrg'])->name('detailbrg');
    Route::resource('supplier', SupplierController::class);
    Route::get('/dashboardadm', [DashboardAdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::match(['get','post'],'/lapmasuk', [TransaksiMasukController::class, 'lapmasuk'])->name('lapmasuk');
    Route::match(['get','post'],'/lapmasuk/export', [TransaksiMasukController::class, 'exportPDF'])->name('export_lapmasuk');
    Route::match(['get', 'post'], '/lapkeluar', [TransaksiKeluarController::class, 'lapkeluar'])->name('lapkeluar');
    Route::match(['get','post'],'/lapkeluar/export', [TransaksiKeluarController::class, 'exportPDF'])->name('export_lapkeluar');
    Route::get('/lapsupplier', [SupplierController::class, 'lapSupplier'])->name('lapSupplier');
    Route::match(['get','post'],'/lapsupplier/export', [SupplierController::class, 'exportPDF'])->name('export_lapsupplier');
    Route::match(['get', 'post'], '/lapretur', [ReturBarangController::class, 'lapretur'])->name('lapretur');
    Route::match(['get','post'],'/lapretur/export', [ReturBarangController::class, 'exportPDF'])->name('export_lapretur');
    Route::match(['get', 'post'], '/lappenggantian', [PenggantianBarangController::class, 'lappenggantian'])->name('lappenggantian');
    Route::match(['get','post'],'/lappenggantian/export', [PenggantianBarangController::class, 'exportPDF'])->name('export_lappenggantian');
});

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home.user');
Route::get('/welcome', [DashboardController::class, 'dashboard'])->name('home.welcome');
// Route::resource('/kategori', [KategoriBarangController::class]);
Route::get('/petugas', [HomeController::class, 'pengguna'])->name('petugas.pengguna');
Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('petugas.dashboard');
Route::resource('petugas', PetugasController::class);
Route::resource('kategori', KategoriBarangController::class);
Route::resource('satuan', SatuanBarangController::class);

Route::resource('retur', ReturBarangController::class);
Route::resource('barang', BarangController::class);
Route::resource('trmasuk', TransaksiMasukController::class);
Route::post('trmasuk/filterTransMasuk', [TransaksiMasukController::class, 'filterTransMasuk'])->name('trmasuk.filterTransMasuk');
Route::get('/modal-content', [TransaksiMasukController::class, 'modalContent'])->name('trmasuk.modalContent');
Route::resource('toko', TokoController::class);
Route::resource('trkeluar', TransaksiKeluarController::class);
Route::post('trkeluar/filterTransKeluar', [TransaksiKeluarController::class, 'filterTransKeluar'])->name('trkeluar.filterTransKeluar');
Route::resource('detailbrg', DetailBarangController::class);
Route::resource('detailmasuk', DetailMasukController::class);
Route::get('/detail_masuk/fetch', [DetailMasukController::class, 'fetch'])->name('detail_masuk.fetch');
Route::resource('detailkeluar', DetailKeluarController::class);
Route::get('/get_stok/{idDetailBarang}', [DetailKeluarController::class, 'getStok']);
Route::resource('detailretur', DetailReturController::class);
Route::get('/retur_stok/{idDetailBarang}', [DetailReturController::class, 'stokRetur']);
Route::resource('penggantianbarang', PenggantianBarangController::class);
Route::get('/get_jumlah_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getJumlahRetur'])->name('retur.getJumlahRetur');
Route::get('/get_detail_retur/{idDetailRetur}', [PenggantianBarangController::class, 'getDetailRetur']);
Route::get('/get_detail_barang/{idDetailBarang}', [PenggantianBarangController::class, 'getDetailBarang']);
Route::get('/get-supplier-name', [DetailMasukController::class, 'getSupplierName']);

app/Models/KategoriBarang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class KategoriBarang extends Model
{
    use HasFactory;
    protected $table = 'kategori_barangs';
    protected $primaryKey = 'idKategori';
    protected $keyType = 'string';
    protected $fillable = [
        'idKategori',
        'namaKategori',
    ];
}

app/Http/Controllers/KategoriBarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\KategoriBarang;

class KategoriBarangController extends Controller
{
    public function index()
    {
        $kategori = KategoriBarang::paginate(5);
        return view('petugas.kategori_barang.index')->with('kategori_barangs', $kategori);
    }

    public function create()
    {
        return view('petugas.kategori_barang.create');
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'idKategori' => 'required',
            'namaKategori' => 'required',
        ]);
        //fungsi eloquent untuk menambah data
        KategoriBarang::create($request->all());
        //jika data berhasil ditambahkan, akan kembali ke halaman utama
        return redirect()->route('kategori.index')->with('success', 'KAtegori Barang Berhasil Ditambahkan');
    }

    public function destroy($idKategori)
    {
        KategoriBarang::find($idKategori)->delete();
        return redirect()->route('kategori.index')
            ->with('success', 'Kategori Barang Berhasil Dihapus');
    }

    public function show($idKategori)
    {
        $kategori = KategoriBarang::find($idKategori);
        $showModal = true;
        return view('petugas.kategori_barang.detail', compact('kategori', 'showModal'));
    }
    
    public function edit($idKategori)
    {
        $kategori = KategoriBarang::find($idKategori);
        $showModal = true;
        return view('petugas.kategori_barang.edit', compact('kategori', 'showModal'));
    }

    public function update(Request $request, string $idKategori)
    {
        //melakukan validasi data
        $request->validate([
            'idKategori' => 'required',
            'namaKategori' => 'required',
        ]);
        //fungsi eloquent untuk mengupdate data inputan kita
        KategoriBarang::find($idKategori)->update($request->all());
        //jika data berhasil diupdate, akan kembali ke halaman utama
        return redirect()->route('kategori.index')->with('success', 'Kategori Barang Berhasil Diupdate');
    }

    public function adminKategori()
    {
        $adminKategori = KategoriBarang::paginate(5);
        return view('admin.kategori_barang.index', compact('adminKategori'));
    }
}

app/Http/Controllers/PetugasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class PetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pengguna = User::where('role', '=', "0")->paginate(3);
        return view('petugas.index')->with('pengguna', $pengguna);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('petugas.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'idUser' => 'required',
            'nama' => 'required',
            'umur' => 'required',
            'alamat' => 'required',
            'username' => 'required',
            'password' => 'required',
            'noTelp' => 'required',
        ]);

        // Menggunakan Hash::make untuk mengenkripsi password
        $requestData = $request->all();
        $requestData['password'] = Hash::make($request->password);

        //fungsi eloquent untuk menambah data
        User::create($requestData);
        //jika data berhasil ditambahkan, akan kembali ke halaman utama
        return redirect()->route('petugas.index')->with('success', 'Petugas Berhasil Ditambahkan');
    }


    /**
     * Display the specified resource.
     */
    public function show($idUser)
    {
        $petugas = User::find($idUser);
        $showModal = true;
        return view('petugas.detail', compact('petugas', 'showModal'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($idUser)
    {
        $petugas = User::find($idUser);
        $showModal = true;
        return view('petugas.edit', compact('petugas', 'showModal'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $idUser)
    {
        //melakukan validasi data
        $request->validate([
            'idUser' => 'required',
            'nama' => 'required',
            'umur' => 'required',
            'alamat' => 'required',
            'username' => 'required',
            'password' => 'required',
            'noTelp' => 'required',
        ]);

        // Menggunakan Hash::make untuk mengenkripsi password
        $requestData = $request->all();
        $requestData['password'] = Hash::make($request->password);

        //fungsi eloquent untuk mengupdate data inputan kita
        User::find($idUser)->update($requestData);
        //jika data berhasil diupdate, akan kembali ke halaman utama
        return redirect()->route('petugas.index')->with('success', 'Petugas Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($idUser)
    {
        User::find($idUser)->delete();
        return redirect()->route('petugas.index')
            ->with('success', 'Petugas Berhasil Dihapus');
    }
}

resources/views/petugas/kategori_barang/create.blade.php
@extends('petugas.app_petugas')
@section('content')
<div class="container mt-5">
   <div class="row justify-content-center align-items-center">
   <div class="card" style="width: 24rem;">
   <div class="card-header">Tambah Kategori Barang</div>
   
   <div class="card-body">
      @if ($errors->any())
      <div class="alert alert-danger">      
         <strong>Whoops!</strong> There were some problems with your input.<br><br>
         <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div>
      @endif
      
      <form method="post" action="{{ route('kategori.store') }}" id="myForm">
         @csrf
         <div class="form-group">
            <label for="idKategori">ID Kategori</label> 
            <input type="text" name="idKategori" class="form-control" id="idKategori" aria-describedby="idKategori" > 
         </div>
         <div class="form-group">
            <label for="namaKategori">Nama Kategori</label> 
            <input type="text" name="namaKategori" class="form-control" id="namaKategori" aria-describedby="namaKategori" > 
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>
</div>
</div>
</div>
@endsection

resources/views/petugas/kategori_barang/detail.blade.php
@extends('petugas.app_petugas')
@section('content')
<head>
    <link rel="stylesheet" href="{{asset('assets/css/kategori.css')}}">
</head>
@if($showModal)
<script>
    $(document).ready(function() {
        $('#modalShow').modal('show');
    });
</script>
@endif

<div class="modal fade" id="modalShow">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Detail Kategori Barang</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>ID Kategori</b>{{$kategori->idKategori}}</li>
                <li class="list-group-item"><b>Nama Kategori</b>{{$kategori->namaKategori}}</li>
            </ul>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('kategori.index') }}">Kembali</a>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/petugas/kategori_barang/edit.blade.php
@extends('petugas.app_petugas')
@section('content')
@if($showModal)
<head>
    <link rel="stylesheet" href="{{asset('assets/css/kategori.css')}}">
</head>
<script>
    $(document).ready(function() {
        $('#modalEdit').modal('show');
    });
</script>
@endif
<div class="modal fade" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Edit Kategori Barang</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="post" action="{{ route('kategori.update', $kategori->idKategori) }}" id="myForm">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="idKategori">ID Kategori Barang</label>
                        <input type="text" name="idKategori" class="form-control" id="idKategori" value="{{ $kategori->idKategori }}" aria-describedby="idKategori">
                    </div>
                    <div class="form-group">
                        <label for="namaKategori">Nama Kategori Barang</label>
                        <input type="text" name="namaKategori" class="form-control" id="namaKategori" value="{{ $kategori->namaKategori }}" aria-describedby="namaKategori">
                    </div>
                    <button type="submit" class="btn btn-submit">Submit</button>
                </form>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <a class="btn btn-primary" href="{{ route('kategori.index') }}">Kembali</a>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/petugas/kategori_barang/index.blade.php
@extends('petugas.app_petugas')
@section('content')
<head>
    <link rel="stylesheet" href="{{asset('assets/css/kategori.css')}}">
</head>

<br>
<div class="col-md-12 d-flex flex-row justify-content-end" data-toggle="modal" data-target="#myModal">
    <a class="btn btn-rounded-pill" style="background-color: #2D7FC1; color: white; padding: 12px 16px; font-size: 24px; margin-left: -8px;">
        <i class="fas fa-plus"></i>
    </a>
</div>
<section class="content-header">
    <div class="container-fluid">
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title font-weight-bold" style="margin-top: 15px;">Kategori Barang</h3><br>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID Kategori</th>
                            <th>Nama Kategori</th>
                            <th width="280px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($kategori_barangs as $k)
                        <tr>
                            <td>{{ $k->idKategori }}</td>
                            <td>{{ $k->namaKategori }}</td>
                            <td>
                                <form action="{{ route('kategori.destroy', $k->idKategori) }}" method="POST">
                                    <a class="btn-action btn-show" href="{{ route('kategori.show', $k->idKategori) }}">Show</a>
                                    <a class="btn-action btn-edit" href="{{ route('kategori.edit', $k->idKategori) }}">Edit</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-action btn-delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tambah Kategori Barang</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ route('kategori.store') }}" id="myForm">
                    @csrf
                    <div class="form-group">
                        <label for="idKategori">ID Kategori</label>
                        <input type="text" name="idKategori" class="form-control" id="idKategori" aria-describedby="idKategori">
                    </div>
                    <div class="form-group">
                        <label for="namaKategori">Nama Kategori</label>
                        <input type="text" name="namaKategori" class="form-control" id="namaKategori" aria-describedby="namaKategori">
                    </div>
                    <button type="submit" class="btn btn-submit">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
    <ul class="pagination">
        {{ $kategori_barangs->links() }}
    </ul>
</div>
@endsection